apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    isDefault: true
    url: timescaledb:5432
    user: hiereb
    secureJsonData:
      password: hiereb_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
